### ISSUE TITLE
hash_key_t.str really should be const

### ISSUE THREAD

**Issue by pprindeville** [SSSD/ding-libs#1]
I'm looking at:

```
typedef struct hash_key_t {
    hash_key_enum type;
    union {
        char *str;
        unsigned long ul;
    };
} hash_key_t;
```

and shouldn't `str` be of type `const char *` instead?  The library should never modify it.

Which means that `convert_key` should also use type `const unsigned char *` instead.

I don't think the other functions touching `.str` will care too much about it's signed-ness.

Or `str` could be changed to `const unsigned char *` and that would probably make more sense.

Well, it's the const-ness that I care about most: in my code which uses this library I have to drop the `const` when initializing a `hash_key_t` object which is kind of unfortunate, especially since `str` never gets written to.

**Comment by alexey-tikhonov** [comment]
Fixed (in some sense) via f085b9b26f6e00cec4a0acf6896843436234ca4f
