### ISSUE TITLE
Test Case Failure - ini_config_ut, ini_save_ut 

### ISSUE THREAD

**Issue by navinagaraj** [SSSD/ding-libs#24]
Hi I tried to update ding-libs to the upstream version while running the test cases I am facing some issues can anyone help? are any dependency packages required?

Architecture  -> armv7l.
Kernel-Version -> 5.4.
Debian distribution.

![ding-libs-error](https://user-images.githubusercontent.com/42691369/194531604-884525ce-7842-4503-9a17-184aef7dcfcb.png)

**Comment by alexey-tikhonov** [comment]
Hi.

> while running the test cases

Why do you run tests this way (as on screenshot)?
Most simple way to run all tests is `make check` in top folder.

The issue in your case is that test tries to open `./ini.conf` that doesn't exist in this dir.
Change folder to `ini` and run
```
$ ../build/test-driver --test-name ini_config_ut --log-file ini_config_ut.log --trs-file ini_config_ut.trs --enable-hard-errors yes --expect-failure no -- ../ini_config_ut
```

**Comment by navinagaraj** [comment]
Hi, @alexey-tikhonov ,
I need to run manually the test cases Because of cross compiling,Thanks for your quick response its works,But the second test case  any Permissions issue ?

**Comment by alexey-tikhonov** [comment]
What is the result of `make check`?

**Comment by navinagaraj** [comment]
cannot execute binary file: Exec format error in *.log files.
![Screenshot from 2022-10-10 18-32-46](https://user-images.githubusercontent.com/42691369/194872992-01b5d992-9f14-4b2a-992b-9b7241bdd843.png)

**Comment by navinagaraj** [comment]
cannot execute binary file: Exec format error  in *.log files
![Screenshot from 2022-10-10 18-37-31](https://user-images.githubusercontent.com/42691369/194873587-5504fc4d-6404-459b-8d54-d21c2878fa49.png)

**Comment by alexey-tikhonov** [comment]
But you can run all those tests manually, like
`$ ./ini_save_ut`?

**Comment by alexey-tikhonov** [comment]
Do you build natively or do you use cross-compiler?

**Comment by navinagaraj** [comment]
> But you can run all those tests manually, like `$ ./ini_save_ut`?

yes.


> Do you build natively or do you use cross-compiler?

Cross-compiler

**Comment by alexey-tikhonov** [comment]
Can you build natively for a testing purpose?

I'd suggest to add additional prints into this test to figure out why `ini_config_save_as()` fails.

**Comment by navinagaraj** [comment]
> Can you build natively for a testing purpose?
> 
> I'd suggest to add additional prints into this test to figure out why `ini_config_save_as()` fails.

Yes build natively,All test cases successfully passed

**Comment by navinagaraj** [comment]
> Can you build natively for a testing purpose?
> 
> I'd suggest to add additional prints into this test to figure out why `ini_config_save_as()` fails.

Yes i build for natively (Ubuntu 20.04.5 LTS )and the test cases are passed.But while cross-compile i am facing the same issue.

**Comment by alexey-tikhonov** [comment]
I guess there is an issue in your env setup.

**Comment by alexey-tikhonov** [comment]
Most probably duplicate of #26
