### ISSUE TITLE
Tests fail -- ini_parse_ut | ini_augment_ut | ini_save_ut

### ISSUE THREAD

**Issue by gdonval** [SSSD/ding-libs#26]
## Versions

- `glibc 2.40`
- `ding 0.6.2`

## Test suite log

```
$ make check
```

```
=======================================
   ding-libs 0.6.2: ./test-suite.log
=======================================

# TOTAL: 14
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: ini_parse_ut
==================

Failed to open file ./ini/ini.d/real16be.conf for reading. Error 22.
FAIL ini_parse_ut (exit status: 22)

FAIL: ini_augment_ut
====================

Files ./merge.validator.in2 and ./merge.validator.out2 differ
Failed to run diff command 256 1.
Failed with error -1!
FAIL ini_augment_ut (exit status: 255)

FAIL: ini_save_ut
=================

Failed to save file as ./test_real16be.conf. Error 22.
Failed with error 22!
FAIL ini_save_ut (exit status: 22)
```

## Extra info

- Said files do exist.
- They don't show correctly in `less`: the encoding seems to not be understood.
- This could be a matter of missing dependency given that the system I build in is minimal (on purpose).

## Sample

```
$ head ./ini/ini.d/real16be.conf
��// This is a real file with some comments

[config]
version = 0.1

/**/
[monitor]
description = Monitor Configuration
sbusTimeout = 10
sbusAddress = unix:path=/var/lib/sss/pipes/private/dbus
```

**Comment by gdonval** [comment]
Solved: missing gettext. It would be awfully *nice* to document what is required to build (with passing checks), sc. `make`, `file`, `check`, `diff`, `gcc` and `gettext`.

**Comment by alexey-tikhonov** [comment]
> Solved: missing gettext. It would be awfully _nice_ to document what is required to build (with passing checks), sc. `make`, `file`, `check`, `diff`, `gcc` and `gettext`.

Please feel free to open a PR.

**Comment by gdonval** [comment]
Of course! Done :)
