### ISSUE TITLE
Problem with path_utils_ut.c on musl

### ISSUE THREAD

**Issue by HRio** [SSSD/ding-libs#5]
Hi I am having problems with this unit test with musl libc

`./path_utils/path_utils_ut.c`
```C
fail_unless(get_dirname(p, PATH_MAX, "//foo//") == SUCCESS);
fail_unless_str_equal(p, "//");
```

Result
```
Running suite(s): path_utils
95%: Checks: 24, Failures: 1, Errors: 0
path_utils/path_utils_ut.c:65:F:path_utils:test_dirname:0: The strings '/' and '//' are different, expected same
FAIL path_utils_ut (exit status: 1)
```

For reference http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_266
> Multiple successive slashes are considered to be the same as one slash

Hence it would seem like a test problem?

With this diff it will pass on musl
```diff
--- ding-libs-0.6.1/path_utils/path_utils_ut.c
+++ ding-libs-0.6.1-path-utils/path_utils/path_utils_ut.c
@@ -62,7 +62,14 @@
     fail_unless_str_equal(p, "//foo");

     fail_unless(get_dirname(p, PATH_MAX, "//foo//") == SUCCESS);
-    fail_unless_str_equal(p, "//");
+    //fail_unless_str_equal(p, "//");
+    fail_unless_str_equal(p, "/");
+
+    fail_unless(get_dirname(p, PATH_MAX, "//") == SUCCESS);
+    fail_unless_str_equal(p, "/");
+
+    fail_unless(get_dirname(p, PATH_MAX, "/") == SUCCESS);
+    fail_unless_str_equal(p, "/");

     fail_unless(get_dirname(p, PATH_MAX, "foo//bar") == SUCCESS);
     fail_unless_str_equal(p, "foo");
```

**Comment by mzidek-gh** [comment]
I think both '//' and '/' should be treated as valid results from the get_dirname in this case. So the condition should be something like:

`fail_unless(!strcmp(p, "/") || !strcmp(p, "//"));`

Untested so there may be typos, but you get the idea :) Feel free to open PR (on Github or Pagure).

**Comment by HRio** [comment]
@mzidek-rh did you see PR #6 ?

**Comment by mzidek-gh** [comment]
@HRio no, for some reason I did not get notification, looking at it now

**Comment by mzidek-gh** [comment]
Pushed to master:
commit 4236e323e8ab4f13770e1ac9e94666b304b693fb
