### ISSUE TITLE
Running tests fail in ini_validators_ut_check

### ISSUE THREAD

**Issue by andreasbaumann** [SSSD/ding-libs#7]
```
94%: Checks: 18, Failures: 1, Errors: 0
ini/ini_validators_ut_check.c:610:F:ini_allowed_options:test_ini_allowed_options_wrong_regex:0: Got msg: [[r
ule/options_for_foo]: Cannot compile regular expression from option 'section_re'. Error: 'Unmatched [, [^, [
:, [., or [=']
FAIL ini_validators_ut_check (exit status: 1)
```

**Comment by mzidek-gh** [comment]
Hi,
what version of libc and ding-libs was used?

**Comment by andreasbaumann** [comment]
glibc 2.28 and ding-libs 0.6.1.
I think, the error message has been improved in glibc (those are standard regex, right?).

**Comment by andreasbaumann** [comment]
mmh. worst case: you have to make a glibc version guard around the check or you could do a more
tolerant test just checking the beginning of the string.

**Comment by mzidek-gh** [comment]
Sorry I should have been more specific about the version. I wanted to know if this was failing with git master. Because I recently added https://github.com/SSSD/ding-libs/commit/9f9a3ded23cc2bb917468939b745cc498cec523a

But I do not know what version of glibc it worked with. I will check this later.

**Comment by andreasbaumann** [comment]
Thanks, yes. commit 9f9a3de fixes it also in my case.
Will backport the patch and then wait for the new release.
Thanks again.

**Comment by andreasbaumann** [comment]
Referencing here for completeness:

https://git.archlinux32.org/archlinux32/packages/src/branch/master/core/ding-libs/ding-libs-0.6.1-ini_validators_ut_check-glibc-2.28.patch
https://bugs.archlinux.org/task/60089
